<?php

namespace AppBundle\Repository;

/**
 * LeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
