<?php

namespace AppBundle\Repository;

/**
 * ProduitToServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitToServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
