<?php

namespace AppBundle\Repository;

/**
 * ProduitToProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitToProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
