<?php

namespace AppBundle\Repository;

/**
 * ServiveToServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiveToServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
