<?php

namespace AppBundle\Repository;

/**
 * ServiceToProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceToProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
