imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    default_locale: 'fr'
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    translator: { fallbacks: [ "fr" ] }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    entities:
        Categorie:
            class: AppBundle\Entity\Categorie
            form:
                fields:
                  - { property: 'designation', label: "Designation"}
                  - { property: 'description', label: "Description"}
                  - { property: "zones", label: "Zones", type: collection , type_options: {entry_type: 'AppBundle\Form\ZoneType', allow_add: true, allow_delete: true, by_reference: false}}

        Zone:
            class: AppBundle\Entity\Zone
            form:
                fields:
                  - { property: "categorie"}
                  - { property: "designation", label: "Designation"}
                  - { property: "description", label: "Description"}
                  - { property: "produits", label: "Produits delivrés", type: collection , type_options: {entry_type: 'AppBundle\Form\ProduitType', allow_add: true, allow_delete: true, by_reference: false}}
        Produit:

            class: AppBundle\Entity\Produit
            form:
              fields:
                - { property: "zone" }
                - { property: "designation" }
                - { property: "details" }
                - { property: "photo", type: "file", type_options: {data_class: null}}
            list:
                actions: ["edit", "show"]
                fields:
                - { property: "photo", type: "image", base_path: "/uploads/produit" }
                - { property: "designation" }
                - { property: "zone" }

        ServiceToServive:
            class: AppBundle\Entity\ServiveToService
        ServiceToProduit:
            class: AppBundle\Entity\ServiceToProduit
        ProduitToProduit:
            class: AppBundle\Entity\ProduitToProduit
        ProduitToService:
            class: AppBundle\Entity\ProduitToService
        Service:
            class: AppBundle\Entity\Service
            list:
                fields:
                  - { property: "photo", type: "image", base_path: "/uploads/service" }
                  - { property: "zone"}
                  - { property: "designation" }
            form:
              fields:
                - { property: "designation" }
                - { property: "zone" }
                - { property: "photo", type: "file", type_options: {data_class: null}}

        Demande:
            class: AppBundle\Entity\Demande
            list:
                actions: ["edit", "show"]
                fields:
                  - { property: "nom"}
                  - { property: "raison" }
                  - { property: "statut", type: 'toggle' }
        Temoignage:
            class: AppBundle\Entity\Temoignage
            form:
                fields:
                  - { property: "nom" }
                  - { property: "contenu" }
                  - { property: "photo", type: "file", type_options: {data_class: null}}
            list:
                fields:
                  - { property: "photo", type: "image", base_path: "/uploads/temoin" }
                  - { property: "nom" }
                  - { property: "contenu" }

    site_name: 'TROC-ZONE <em style="font-size: 80%;">Administration</em>'
    design:
      menu:
          - {entity : "Categorie", icon: "list", label: "Categorie"}
          - {entity : "Zone", icon: "group"}
          - {entity : "Produit", icon: "ship"}
          - {entity : "Service", icon: "asl-interpreting"}
          - {entity : "Demande"}
          - {entity : "Temoignage"}
          - label: "Echanges"
            icon: "user"
            children:
                  - { label: 'Service-Service', entity: "ServiceToServive" }
                  - { label: 'Service-Produit', entity: 'ServiceToProduit' }
                  - { label: 'Produit-Produit', entity: 'ProduitToProduit' }
                  - { label: 'Produit-Service', entity: 'ProduitToService' }

