app:
    resource: "@AppBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /page/admin

user_registration:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }
